/**
 * Publisher ids that exist in the registry.
 *
 * GENERATED by `scripts/generate-registry-ids.mjs` — do not edit. Run
 * `pnpm run registry:ids` after adding or removing an entry;
 * `registry:ids --check` fails CI when this file has drifted from the tree.
 */

export const REGISTRY_IDS: ReadonlySet<string> = new Set([
  'corag',
  'pereira-ayuda',
  'pereira-responde',
  'reporte-co',
]);
